export type ExportColorSpace =
  | "srgb"
  | "display-p3"
  | "adobe-rgb"
  | "prophoto-rgb";

const clamp01 = (value: number) => Math.max(0, Math.min(1, value));

const decodeSrgb = (value: number) =>
  value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;

const encodeGamma = (value: number, gamma: number) =>
  clamp01(value) ** (1 / gamma);

const multiply3 = (matrix: number[], vector: number[]) => [
  matrix[0] * vector[0] + matrix[1] * vector[1] + matrix[2] * vector[2],
  matrix[3] * vector[0] + matrix[4] * vector[1] + matrix[5] * vector[2],
  matrix[6] * vector[0] + matrix[7] * vector[1] + matrix[8] * vector[2],
];

const xyzToRgb: Record<ExportColorSpace, number[]> = {
  srgb: [3.2406, -1.5372, -0.4986, -0.9689, 1.8758, 0.0415, 0.0557, -0.204, 1.057],
  "display-p3": [2.4935, -0.9314, -0.4027, -0.8295, 1.7627, 0.0236, 0.0358, -0.0762, 0.9569],
  "adobe-rgb": [2.0416, -0.565, -0.3447, -0.9692, 1.876, 0.0416, 0.0134, -0.1184, 1.0154],
  "prophoto-rgb": [1.3459, -0.2556, -0.0511, -0.5446, 1.5082, 0.0205, 0, 0, 1.2123],
};

const gamma: Record<ExportColorSpace, number> = {
  srgb: 2.4,
  "display-p3": 2.4,
  "adobe-rgb": 2.19921875,
  "prophoto-rgb": 1.8,
};

/** Converts the canvas' sRGB pixels into the selected export RGB space. */
export function convertImageColorSpace(
  source: ImageData,
  target: ExportColorSpace,
) {
  if (target === "srgb") return source;
  const output = new ImageData(
    new Uint8ClampedArray(source.data),
    source.width,
    source.height,
  );
  const srgbToXyz = [
    0.4124564, 0.3575761, 0.1804375, 0.2126729, 0.7151522, 0.072175,
    0.0193339, 0.119192, 0.9503041,
  ];
  const d65ToD50 = [
    1.0478112, 0.0228866, -0.050127, 0.0295424, 0.9904844, -0.0170491,
    -0.0092345, 0.0150436, 0.7521316,
  ];
  for (let offset = 0; offset < output.data.length; offset += 4) {
    const linear = [
      decodeSrgb(source.data[offset] / 255),
      decodeSrgb(source.data[offset + 1] / 255),
      decodeSrgb(source.data[offset + 2] / 255),
    ];
    let xyz = multiply3(srgbToXyz, linear);
    if (target === "prophoto-rgb") xyz = multiply3(d65ToD50, xyz);
    const converted = multiply3(xyzToRgb[target], xyz);
    output.data[offset] = Math.round(encodeGamma(converted[0], gamma[target]) * 255);
    output.data[offset + 1] = Math.round(
      encodeGamma(converted[1], gamma[target]) * 255,
    );
    output.data[offset + 2] = Math.round(
      encodeGamma(converted[2], gamma[target]) * 255,
    );
  }
  return output;
}

const ascii = (value: string) =>
  new TextEncoder().encode(value.endsWith("\0") ? value : `${value}\0`);

const be32 = (value: number) => {
  const bytes = new Uint8Array(4);
  new DataView(bytes.buffer).setUint32(0, value, false);
  return bytes;
};

const s15Fixed16 = (value: number) => {
  const bytes = new Uint8Array(4);
  new DataView(bytes.buffer).setInt32(0, Math.round(value * 65536), false);
  return bytes;
};

const concat = (...parts: Uint8Array[]) => {
  const output = new Uint8Array(parts.reduce((sum, part) => sum + part.length, 0));
  let offset = 0;
  for (const part of parts) {
    output.set(part, offset);
    offset += part.length;
  }
  return output;
};

const pad4 = (data: Uint8Array) => {
  const padding = (4 - (data.length % 4)) % 4;
  return padding ? concat(data, new Uint8Array(padding)) : data;
};

function iccTextTag(value: string) {
  const text = ascii(value);
  return pad4(concat(ascii("desc").slice(0, 4), new Uint8Array(4), be32(text.length), text));
}

function iccXyzTag(values: number[]) {
  return concat(ascii("XYZ ").slice(0, 4), new Uint8Array(4), ...values.map(s15Fixed16));
}

function iccCurveTag(profileGamma: number) {
  const bytes = new Uint8Array(14);
  bytes.set(ascii("curv").slice(0, 4));
  const view = new DataView(bytes.buffer);
  view.setUint32(8, 1, false);
  view.setUint16(12, Math.round(profileGamma * 256), false);
  return pad4(bytes);
}

/** Creates a compact matrix ICC v2 profile suitable for embedding in TIFF/DNG. */
export function createIccProfile(space: ExportColorSpace) {
  const names: Record<ExportColorSpace, string> = {
    srgb: "LibreLux sRGB",
    "display-p3": "LibreLux Display P3",
    "adobe-rgb": "LibreLux Adobe RGB (1998)",
    "prophoto-rgb": "LibreLux ProPhoto RGB",
  };
  const primaries: Record<ExportColorSpace, number[][]> = {
    srgb: [[0.4361, 0.2225, 0.0139], [0.3851, 0.7169, 0.0971], [0.1431, 0.0606, 0.7141]],
    "display-p3": [[0.5151, 0.2412, -0.0011], [0.292, 0.6922, 0.0419], [0.1571, 0.0666, 0.7841]],
    "adobe-rgb": [[0.6098, 0.3111, 0.0195], [0.2052, 0.6257, 0.0609], [0.1492, 0.0632, 0.7446]],
    "prophoto-rgb": [[0.7977, 0.288, 0], [0.1352, 0.7119, 0], [0.0313, 0.0001, 0.8249]],
  };
  const tags = [
    ["desc", iccTextTag(names[space])],
    ["cprt", iccTextTag("Generated by LibreLux; profile names identify standard RGB spaces.")],
    ["wtpt", iccXyzTag([0.9642, 1, 0.8249])],
    ["rXYZ", iccXyzTag(primaries[space][0])],
    ["gXYZ", iccXyzTag(primaries[space][1])],
    ["bXYZ", iccXyzTag(primaries[space][2])],
    ["rTRC", iccCurveTag(gamma[space])],
    ["gTRC", iccCurveTag(gamma[space])],
    ["bTRC", iccCurveTag(gamma[space])],
  ] as const;
  const header = new Uint8Array(128);
  const headerView = new DataView(header.buffer);
  header.set(ascii("mntr").slice(0, 4), 12);
  header.set(ascii("RGB ").slice(0, 4), 16);
  header.set(ascii("XYZ ").slice(0, 4), 20);
  header.set(ascii("acsp").slice(0, 4), 36);
  header.set(ascii("APPL").slice(0, 4), 40);
  header.set(ascii("LLUX").slice(0, 4), 80);
  headerView.setUint32(8, 0x02100000, false);
  const table = new Uint8Array(4 + tags.length * 12);
  const tableView = new DataView(table.buffer);
  tableView.setUint32(0, tags.length, false);
  let dataOffset = header.length + table.length;
  const payload: Uint8Array[] = [];
  tags.forEach(([signature, data], index) => {
    const entry = 4 + index * 12;
    table.set(ascii(signature).slice(0, 4), entry);
    tableView.setUint32(entry + 4, dataOffset, false);
    tableView.setUint32(entry + 8, data.length, false);
    payload.push(data);
    dataOffset += data.length;
  });
  const profile = concat(header, table, ...payload);
  new DataView(profile.buffer).setUint32(0, profile.length, false);
  return profile;
}

type TiffKind = "tiff16" | "dng16" | "tiff32";
type TiffEntry = { tag: number; type: number; count: number; data: Uint8Array };

const u16Array = (values: number[]) => {
  const data = new Uint8Array(values.length * 2);
  const view = new DataView(data.buffer);
  values.forEach((value, index) => view.setUint16(index * 2, value, true));
  return data;
};

const u32Array = (values: number[]) => {
  const data = new Uint8Array(values.length * 4);
  const view = new DataView(data.buffer);
  values.forEach((value, index) => view.setUint32(index * 4, value, true));
  return data;
};

const rationalArray = (values: Array<[number, number]>, signed = false) => {
  const data = new Uint8Array(values.length * 8);
  const view = new DataView(data.buffer);
  values.forEach(([numerator, denominator], index) => {
    if (signed) {
      view.setInt32(index * 8, numerator, true);
      view.setInt32(index * 8 + 4, denominator, true);
    } else {
      view.setUint32(index * 8, numerator, true);
      view.setUint32(index * 8 + 4, denominator, true);
    }
  });
  return data;
};

function encodeTiff(
  width: number,
  height: number,
  pixels: Uint8Array,
  kind: TiffKind,
  colorSpace: ExportColorSpace,
  cameraModel: string,
) {
  const bits = kind === "tiff32" ? 32 : 16;
  const sampleFormat = kind === "tiff32" ? 3 : 1;
  const profile = createIccProfile(colorSpace);
  const entries: TiffEntry[] = [
    { tag: 256, type: 4, count: 1, data: u32Array([width]) },
    { tag: 257, type: 4, count: 1, data: u32Array([height]) },
    { tag: 258, type: 3, count: 3, data: u16Array([bits, bits, bits]) },
    { tag: 259, type: 3, count: 1, data: u16Array([1]) },
    { tag: 262, type: 3, count: 1, data: u16Array([kind === "dng16" ? 34892 : 2]) },
    { tag: 273, type: 4, count: 1, data: u32Array([0]) },
    { tag: 277, type: 3, count: 1, data: u16Array([3]) },
    { tag: 278, type: 4, count: 1, data: u32Array([height]) },
    { tag: 279, type: 4, count: 1, data: u32Array([pixels.byteLength]) },
    { tag: 282, type: 5, count: 1, data: rationalArray([[300, 1]]) },
    { tag: 283, type: 5, count: 1, data: rationalArray([[300, 1]]) },
    { tag: 284, type: 3, count: 1, data: u16Array([1]) },
    { tag: 296, type: 3, count: 1, data: u16Array([2]) },
    { tag: 305, type: 2, count: 16, data: ascii("LibreLux 1.0") },
    { tag: 339, type: 3, count: 3, data: u16Array([sampleFormat, sampleFormat, sampleFormat]) },
    { tag: 34675, type: 7, count: profile.length, data: profile },
  ];
  if (kind === "dng16") {
    entries.push(
      { tag: 50706, type: 1, count: 4, data: new Uint8Array([1, 4, 0, 0]) },
      { tag: 50707, type: 1, count: 4, data: new Uint8Array([1, 3, 0, 0]) },
      { tag: 50708, type: 2, count: ascii(cameraModel).length, data: ascii(cameraModel) },
      { tag: 50717, type: 3, count: 3, data: u16Array([65535, 65535, 65535]) },
      {
        tag: 50721,
        type: 10,
        count: 9,
        data: rationalArray(
          [[10000, 10000], [0, 10000], [0, 10000], [0, 10000], [10000, 10000], [0, 10000], [0, 10000], [0, 10000], [10000, 10000]],
          true,
        ),
      },
      { tag: 50728, type: 5, count: 3, data: rationalArray([[1, 1], [1, 1], [1, 1]]) },
      { tag: 50778, type: 3, count: 1, data: u16Array([21]) },
    );
  }
  entries.sort((a, b) => a.tag - b.tag);
  const ifdOffset = 8;
  const ifdSize = 2 + entries.length * 12 + 4;
  let externalOffset = ifdOffset + ifdSize;
  const external: Uint8Array[] = [];
  const ifd = new Uint8Array(ifdSize);
  const ifdView = new DataView(ifd.buffer);
  ifdView.setUint16(0, entries.length, true);
  entries.forEach((entry, index) => {
    const offset = 2 + index * 12;
    ifdView.setUint16(offset, entry.tag, true);
    ifdView.setUint16(offset + 2, entry.type, true);
    ifdView.setUint32(offset + 4, entry.count, true);
    if (entry.data.length <= 4) ifd.set(entry.data, offset + 8);
    else {
      ifdView.setUint32(offset + 8, externalOffset, true);
      const padded = pad4(entry.data);
      external.push(padded);
      externalOffset += padded.length;
    }
  });
  const pixelOffset = externalOffset;
  const stripEntry = entries.findIndex((entry) => entry.tag === 273);
  ifdView.setUint32(2 + stripEntry * 12 + 8, pixelOffset, true);
  const header = new Uint8Array(8);
  header[0] = 0x49;
  header[1] = 0x49;
  const headerView = new DataView(header.buffer);
  headerView.setUint16(2, 42, true);
  headerView.setUint32(4, ifdOffset, true);
  const parts = [header, ifd, ...external, pixels].map((part) =>
    part.buffer.slice(part.byteOffset, part.byteOffset + part.byteLength) as ArrayBuffer,
  );
  return new Blob(parts, {
    type: kind === "dng16" ? "image/x-adobe-dng" : "image/tiff",
  });
}

export function encodeRgb16(
  image: ImageData,
  kind: "tiff16" | "dng16",
  colorSpace: ExportColorSpace,
  cameraModel = "LibreLux Linear RGB",
) {
  const converted = convertImageColorSpace(image, colorSpace);
  const pixels = new Uint8Array(converted.width * converted.height * 6);
  const view = new DataView(pixels.buffer);
  let target = 0;
  for (let offset = 0; offset < converted.data.length; offset += 4) {
    view.setUint16(target, converted.data[offset] * 257, true);
    view.setUint16(target + 2, converted.data[offset + 1] * 257, true);
    view.setUint16(target + 4, converted.data[offset + 2] * 257, true);
    target += 6;
  }
  return encodeTiff(
    converted.width,
    converted.height,
    pixels,
    kind,
    colorSpace,
    cameraModel,
  );
}

const proPhotoToXyzD50 = [
  0.7976749, 0.1351917, 0.0313534,
  0.2880402, 0.7118741, 0.0000857,
  0, 0, 0.82521,
];
const d50ToD65 = [
  0.9555766, -0.0230393, 0.0631636,
  -0.0282895, 1.0099416, 0.0210077,
  0.0122982, -0.020483, 1.3299098,
];

const encodeSrgb = (value: number) => {
  const safe = clamp01(value);
  return safe <= 0.0031308
    ? safe * 12.92
    : 1.055 * safe ** (1 / 2.4) - 0.055;
};

/** Encode a scene-linear ProPhoto float master directly to real 16-bit RGB. */
export function encodeLinearRgb16(
  image: { width: number; height: number; data: Float32Array },
  kind: "tiff16" | "dng16",
  colorSpace: ExportColorSpace,
  cameraModel = "LibreLux Linear RGB",
) {
  const pixels = new Uint8Array(image.width * image.height * 6);
  const view = new DataView(pixels.buffer);
  let target = 0;
  for (let offset = 0; offset < image.data.length; offset += 3) {
    const proPhoto = [
      Math.max(0, image.data[offset]),
      Math.max(0, image.data[offset + 1]),
      Math.max(0, image.data[offset + 2]),
    ];
    let converted = proPhoto;
    if (colorSpace !== "prophoto-rgb") {
      const xyzD50 = multiply3(proPhotoToXyzD50, proPhoto);
      const xyzD65 = multiply3(d50ToD65, xyzD50);
      converted = multiply3(xyzToRgb[colorSpace], xyzD65);
    }
    const encoded = converted.map((value) =>
      colorSpace === "srgb"
        ? encodeSrgb(value)
        : encodeGamma(value, gamma[colorSpace]),
    );
    view.setUint16(target, Math.round(clamp01(encoded[0]) * 65535), true);
    view.setUint16(target + 2, Math.round(clamp01(encoded[1]) * 65535), true);
    view.setUint16(target + 4, Math.round(clamp01(encoded[2]) * 65535), true);
    target += 6;
  }
  return encodeTiff(
    image.width,
    image.height,
    pixels,
    kind,
    colorSpace,
    cameraModel,
  );
}

export function mergeHdrFloat32(frames: ImageData[]) {
  if (!frames.length) throw new Error("HDR merge needs source frames");
  const { width, height } = frames[0];
  const linear = new Float32Array(width * height * 3);
  for (let pixel = 0; pixel < width * height; pixel++) {
    for (let channel = 0; channel < 3; channel++) {
      let weighted = 0;
      let totalWeight = 0;
      for (const frame of frames) {
        const encoded = frame.data[pixel * 4 + channel] / 255;
        const value = decodeSrgb(encoded);
        const weight = Math.max(0.01, 1 - Math.abs(encoded - 0.5) * 1.9);
        weighted += value * weight;
        totalWeight += weight;
      }
      linear[pixel * 3 + channel] = weighted / totalWeight;
    }
  }
  const toneMapped = new ImageData(width, height);
  for (let pixel = 0; pixel < width * height; pixel++) {
    for (let channel = 0; channel < 3; channel++) {
      const value = linear[pixel * 3 + channel];
      const reinhard = value / (1 + value);
      toneMapped.data[pixel * 4 + channel] = Math.round(
        255 * encodeGamma(reinhard, 2.2),
      );
    }
    toneMapped.data[pixel * 4 + 3] = 255;
  }
  return { linear, toneMapped };
}

export function encodeHdrFloat32(
  width: number,
  height: number,
  linear: Float32Array,
  colorSpace: ExportColorSpace = "prophoto-rgb",
) {
  return encodeTiff(
    width,
    height,
    new Uint8Array(linear.buffer.slice(0)),
    "tiff32",
    colorSpace,
    "LibreLux HDR Float32",
  );
}
