"use client";

import { Aperture, ArrowDownToLine, Columns2, Check, ChevronDown, Crop, Download, Flag, FolderOpen, Grid3X3, ImagePlus, Info, Library, Menu, PanelLeftClose, PanelRightClose, RotateCcw, RotateCw, Search, SlidersHorizontal, Sparkles, Star, Undo2, Redo2, WandSparkles, X, ZoomIn, ZoomOut } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type Workspace = "library" | "develop" | "enhance";
type Label = "none" | "red" | "yellow" | "green" | "blue" | "purple";
type Adjustments = { exposure:number; contrast:number; highlights:number; shadows:number; whites:number; blacks:number; temperature:number; tint:number; vibrance:number; saturation:number; hue:number; texture:number; clarity:number; dehaze:number; vignette:number; vignetteMidpoint:number; vignetteFeather:number; grain:number; grainSize:number; grainRoughness:number; noise:number; colorNoise:number; sharpness:number; sharpRadius:number; sharpDetail:number; sharpMasking:number; lensSharpness:number; lensVignette:number; distortion:number; chromatic:number; defringe:number; perspectiveV:number; perspectiveH:number; perspectiveAspect:number; perspectiveScale:number; offsetX:number; offsetY:number; rotation:number; flipX:number; flipY:number; cropRatio:number; shadowHue:number; shadowSaturation:number; midtoneHue:number; midtoneSaturation:number; highlightHue:number; highlightSaturation:number; gradingBalance:number };
type PhotoMetadata = { title:string; caption:string; creator:string; copyright:string; keywords:string[] };
type PhotoRecord = { id:string; name:string; type:string; size:number; createdAt:number; rating:number; flagged:boolean; rejected:boolean; label:Label; blob:Blob; adjustments:Adjustments; metadata:PhotoMetadata };
type RuntimePhoto = PhotoRecord & { url:string };

declare global {
  interface Document {
    modelContext?: {
      registerTool: (tool: {
        name: string;
        title: string;
        description: string;
        inputSchema: object;
        annotations?: { readOnlyHint?: boolean; untrustedContentHint?: boolean };
        execute: (input: unknown) => unknown | Promise<unknown>;
      }, options?: { signal?: AbortSignal }) => void | Promise<void>;
    };
  }
}

const defaults: Adjustments = { exposure:0,contrast:0,highlights:0,shadows:0,whites:0,blacks:0,temperature:0,tint:0,vibrance:0,saturation:0,hue:0,texture:0,clarity:0,dehaze:0,vignette:0,vignetteMidpoint:50,vignetteFeather:50,grain:0,grainSize:25,grainRoughness:50,noise:0,colorNoise:0,sharpness:20,sharpRadius:1,sharpDetail:25,sharpMasking:0,lensSharpness:0,lensVignette:0,distortion:0,chromatic:0,defringe:0,perspectiveV:0,perspectiveH:0,perspectiveAspect:0,perspectiveScale:100,offsetX:0,offsetY:0,rotation:0,flipX:1,flipY:1,cropRatio:0,shadowHue:220,shadowSaturation:0,midtoneHue:35,midtoneSaturation:0,highlightHue:45,highlightSaturation:0,gradingBalance:0 };
const emptyMetadata: PhotoMetadata = { title:"",caption:"",creator:"",copyright:"",keywords:[] };
const presets = [
  {name:"Clean Light",tone:"#d7dfd0",settings:{exposure:.3,highlights:-18,shadows:22,vibrance:12}},
  {name:"Quiet Film",tone:"#b3a58f",settings:{contrast:-8,blacks:16,grain:24,saturation:-9,temperature:9}},
  {name:"Deep Chrome",tone:"#384d5c",settings:{contrast:24,dehaze:12,vibrance:20,blacks:-16}},
  {name:"Warm Portrait",tone:"#c9896e",settings:{temperature:18,tint:5,texture:-12,vibrance:9}},
  {name:"Silver",tone:"#8e9498",settings:{saturation:-100,contrast:18,clarity:14,grain:18}},
  {name:"Night Air",tone:"#31394e",settings:{exposure:-.35,shadows:26,dehaze:18,temperature:-13}},
] satisfies {name:string;tone:string;settings:Partial<Adjustments>}[];
const labelColors: Record<Label,string> = { none:"transparent",red:"#f46d74",yellow:"#e6c34f",green:"#66bf8d",blue:"#6ca7e8",purple:"#a881d8" };

function openDb(): Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open("librelux-library",1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains("photos"))db.createObjectStore("photos",{keyPath:"id"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function readPhotos():Promise<PhotoRecord[]>{const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction("photos","readonly").objectStore("photos").getAll();r.onsuccess=()=>resolve(r.result as PhotoRecord[]);r.onerror=()=>reject(r.error)})}
async function savePhoto(photo:PhotoRecord){const db=await openDb();return new Promise<void>((resolve,reject)=>{const r=db.transaction("photos","readwrite").objectStore("photos").put(photo);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
async function deletePhoto(id:string){const db=await openDb();return new Promise<void>((resolve,reject)=>{const r=db.transaction("photos","readwrite").objectStore("photos").delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function formatBytes(size:number){return size<1048576?`${Math.max(1,Math.round(size/1024))} KB`:`${(size/1048576).toFixed(1)} MB`}
function cssFilter(a:Adjustments){const tonal=(a.highlights+a.whites-a.blacks+a.shadows)/900;const brightness=Math.max(.12,Math.pow(2,a.exposure)*(1+tonal));const contrast=Math.max(.18,1+a.contrast/100+a.clarity/250+a.dehaze/320+a.sharpness/900+a.lensSharpness/1000);const saturation=Math.max(0,1+a.saturation/100+a.vibrance/160-a.colorNoise/1200);const warmth=Math.abs(a.temperature)/600;const grade=((a.shadowHue*a.shadowSaturation)+(a.midtoneHue*a.midtoneSaturation)+(a.highlightHue*a.highlightSaturation))/Math.max(1,a.shadowSaturation+a.midtoneSaturation+a.highlightSaturation)/20||0;const hue=a.hue+a.tint/8+(a.temperature<0?-a.temperature/16:0)+grade;const blur=Math.max(0,a.noise/180-a.sharpDetail/3000);return `brightness(${brightness}) contrast(${contrast}) saturate(${saturation}) sepia(${warmth}) hue-rotate(${hue}deg) blur(${blur}px)`}

function Histogram({photo}:{photo?:RuntimePhoto}){const seed=photo?photo.name.length*7+Math.round(photo.size/1000):13;const values=Array.from({length:25},(_,i)=>{const h=8+(Math.sin(i*.73+seed)+1)*24+(Math.cos(i*.29+seed)+1)*10;return [i*4.2,64-Math.min(60,h)]});const points=values.map(([x,y])=>`${x},${y}`).join(" ");return <div className="histogram" aria-label="RGB histogram"><svg viewBox="0 0 104 66" preserveAspectRatio="none"><polygon points={`0,64 ${points} 104,64`} fill="rgba(214,230,211,.28)"/><polyline points={points} fill="none" stroke="#c9e6c4" strokeWidth="1.2"/><polyline points={values.map(([x,y],i)=>`${x},${Math.min(64,y+(i%3)*3)}`).join(" ")} fill="none" stroke="#78b6dd" strokeOpacity=".55" strokeWidth=".8"/></svg><div><span>0</span><span>128</span><span>255</span></div></div>}
function ToolButton({label,children,active,onClick}:{label:string;children:React.ReactNode;active?:boolean;onClick?:()=>void}){return <button className={`icon-button ${active?"active":""}`} aria-label={label} title={label} onClick={onClick}>{children}</button>}
function AdjustSlider({label,value,min=-100,max=100,step=1,onChange}:{label:string;value:number;min?:number;max?:number;step?:number;onChange:(value:number)=>void}){const display=step<1?value.toFixed(2):Math.round(value).toString();return <div className="adjust-row"><div className="adjust-label"><span>{label}</span><button onDoubleClick={()=>onChange(0)} title="Double-click to reset">{value>0?"+":""}{display}</button></div><Slider value={[value]} min={min} max={max} step={step} onValueChange={(v)=>onChange(v[0])} aria-label={label}/></div>}
function Panel({title,children,open=true,badge}:{title:string;children:React.ReactNode;open?:boolean;badge?:string}){return <details className="panel" open={open}><summary><ChevronDown size={15}/><span>{title}</span>{badge&&<em>{badge}</em>}</summary><div className="panel-body">{children}</div></details>}

export default function Home(){
  const [workspace,setWorkspace]=useState<Workspace>("develop");const [photos,setPhotos]=useState<RuntimePhoto[]>([]);const [selectedId,setSelectedId]=useState<string|null>(null);const [query,setQuery]=useState("");const [filter,setFilter]=useState<"all"|"flagged"|"rated"|"edited"|"rejected">("all");const [sort,setSort]=useState<"recent"|"name"|"rating"|"size">("recent");const [showBefore,setShowBefore]=useState(false);const [showLeft,setShowLeft]=useState(true);const [showRight,setShowRight]=useState(true);const [cropMode,setCropMode]=useState(false);const [zoom,setZoom]=useState(68);const [exportOpen,setExportOpen]=useState(false);const [exportQuality,setExportQuality]=useState(92);const [exportFormat,setExportFormat]=useState<"jpeg"|"png"|"webp">("jpeg");const [exportScale,setExportScale]=useState(100);const [history,setHistory]=useState<Adjustments[]>([]);const [future,setFuture]=useState<Adjustments[]>([]);const [copiedSettings,setCopiedSettings]=useState<Adjustments|null>(null);const fileRef=useRef<HTMLInputElement>(null);
  const selected=photos.find(p=>p.id===selectedId);const filtered=useMemo(()=>photos.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())&&(filter==="all"||(filter==="flagged"&&p.flagged)||(filter==="rated"&&p.rating>0)||(filter==="rejected"&&p.rejected)||(filter==="edited"&&JSON.stringify(p.adjustments)!==JSON.stringify(defaults)))).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="rating"?b.rating-a.rating:sort==="size"?b.size-a.size:b.createdAt-a.createdAt),[photos,query,filter,sort]);
  useEffect(()=>{readPhotos().then(records=>{const runtime=records.sort((a,b)=>b.createdAt-a.createdAt).map(p=>({...p,rejected:p.rejected??false,metadata:{...emptyMetadata,...p.metadata},adjustments:{...defaults,...p.adjustments},url:URL.createObjectURL(p.blob)}));setPhotos(runtime);const remembered=localStorage.getItem("librelux-selected-photo");const initial=runtime.find(p=>p.id===remembered)??runtime[0];if(initial)setSelectedId(initial.id)}).catch(()=>undefined)},[]);
  useEffect(()=>{if(selectedId)localStorage.setItem("librelux-selected-photo",selectedId)},[selectedId]);
  const updateSelected=useCallback((updater:(photo:RuntimePhoto)=>RuntimePhoto,persist=true)=>{setPhotos(current=>current.map(photo=>{if(photo.id!==selectedId)return photo;const next=updater(photo);if(persist)void savePhoto(next);return next}))},[selectedId]);
  const setAdjustment=useCallback((key:keyof Adjustments,value:number)=>{if(!selected)return;setHistory(h=>[...h.slice(-29),selected.adjustments]);setFuture([]);updateSelected(photo=>({...photo,adjustments:{...photo.adjustments,[key]:value}}))},[selected,updateSelected]);
  const importFiles=useCallback(async(fileList:FileList|File[])=>{const files=Array.from(fileList).filter(file=>file.type.startsWith("image/"));const imported=files.map(file=>{const record:PhotoRecord={id:crypto.randomUUID(),name:file.name,type:file.type,size:file.size,createdAt:Date.now(),rating:0,flagged:false,rejected:false,label:"none",blob:file,adjustments:{...defaults},metadata:{...emptyMetadata}};void savePhoto(record);return {...record,url:URL.createObjectURL(file)}});setPhotos(p=>[...imported,...p]);if(imported[0]){setSelectedId(imported[0].id);setWorkspace("develop")}},[]);
  const removeSelected=useCallback(()=>{if(!selected)return;void deletePhoto(selected.id);URL.revokeObjectURL(selected.url);const remaining=photos.filter(p=>p.id!==selected.id);setPhotos(remaining);setSelectedId(remaining[0]?.id??null)},[selected,photos]);
  const applyPreset=(settings:Partial<Adjustments>)=>{if(!selected)return;setHistory(h=>[...h.slice(-29),selected.adjustments]);updateSelected(photo=>({...photo,adjustments:{...photo.adjustments,...settings}}))};
  const undo=useCallback(()=>{if(!selected||!history.length)return;const previous=history.at(-1)!;setFuture(f=>[selected.adjustments,...f]);setHistory(h=>h.slice(0,-1));updateSelected(p=>({...p,adjustments:previous}))},[selected,history,updateSelected]);
  const redo=useCallback(()=>{if(!selected||!future.length)return;const next=future[0];setHistory(h=>[...h,selected.adjustments]);setFuture(f=>f.slice(1));updateSelected(p=>({...p,adjustments:next}))},[selected,future,updateSelected]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{const tag=(event.target as HTMLElement)?.tagName;if(tag==="INPUT"||tag==="TEXTAREA")return;const key=event.key.toLowerCase();const mod=event.metaKey||event.ctrlKey;if(mod&&key==="z"){event.preventDefault();event.shiftKey?redo():undo();return}if(mod&&event.shiftKey&&key==="c"&&selected){event.preventDefault();setCopiedSettings(selected.adjustments);return}if(mod&&event.shiftKey&&key==="v"&&selected&&copiedSettings){event.preventDefault();updateSelected(p=>({...p,adjustments:{...copiedSettings}}));return}if(key==="g")setWorkspace("library");if(key==="d")setWorkspace("develop");if(key==="e")setWorkspace("enhance");if(event.key==="\\")setShowBefore(v=>!v);if(key==="p"&&selected)updateSelected(p=>({...p,flagged:true,rejected:false}));if(key==="x"&&selected)updateSelected(p=>({...p,rejected:true,flagged:false}));if(key==="u"&&selected)updateSelected(p=>({...p,rejected:false,flagged:false}));if(/^[0-5]$/.test(key)&&selected)updateSelected(p=>({...p,rating:Number(key)}))};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[redo,undo,selected,updateSelected,copiedSettings]);
  useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=async()=>{await context.registerTool({name:"open_workspace",title:"Open LibreLux workspace",description:"Open the Library, Develop, or Enhance workspace in LibreLux.",inputSchema:{type:"object",properties:{workspace:{type:"string",enum:["library","develop","enhance"]}},required:["workspace"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const value=(input as {workspace?:unknown})?.workspace;if(value!=="library"&&value!=="develop"&&value!=="enhance")throw new Error("workspace must be library, develop, or enhance");setWorkspace(value);return{workspace:value}}},{signal:lifecycle.signal});await context.registerTool({name:"set_photo_rating",title:"Rate selected photo",description:"Set the selected LibreLux photo rating from zero to five stars.",inputSchema:{type:"object",properties:{rating:{type:"integer",minimum:0,maximum:5}},required:["rating"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const rating=(input as {rating?:unknown})?.rating;if(!Number.isInteger(rating)||Number(rating)<0||Number(rating)>5)throw new Error("rating must be an integer from 0 to 5");if(!selected)throw new Error("No photo is selected");updateSelected(photo=>({...photo,rating:Number(rating)}));return{photoId:selected.id,rating}}},{signal:lifecycle.signal})};void register().catch(()=>undefined);return()=>lifecycle.abort()},[selected,updateSelected]);
  const autoEnhance=()=>applyPreset({exposure:.18,highlights:-24,shadows:28,whites:8,blacks:-8,vibrance:13,clarity:7,dehaze:5,noise:18,colorNoise:22,sharpness:38,lensSharpness:28,chromatic:18});
  const doExport=async()=>{
    if(!selected)return;
    const image=new Image();image.src=selected.url;await image.decode();
    const factor=exportScale/100;let sx=0,sy=0,sw=image.naturalWidth,sh=image.naturalHeight;const ratio=selected.adjustments.cropRatio;
    if(ratio>0){const original=sw/sh;if(original>ratio){const next=sh*ratio;sx=(sw-next)/2;sw=next}else{const next=sw/ratio;sy=(sh-next)/2;sh=next}}
    const rotated=Math.abs(selected.adjustments.rotation%180)===90;const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round((rotated?sh:sw)*factor));canvas.height=Math.max(1,Math.round((rotated?sw:sh)*factor));const ctx=canvas.getContext("2d");if(!ctx)return;
    ctx.filter=cssFilter(selected.adjustments);ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(selected.adjustments.rotation*Math.PI/180);ctx.scale(selected.adjustments.flipX,selected.adjustments.flipY);ctx.drawImage(image,sx,sy,sw,sh,-sw*factor/2,-sh*factor/2,sw*factor,sh*factor);if(selected.adjustments.chromatic>0){ctx.save();ctx.globalCompositeOperation="screen";ctx.globalAlpha=Math.min(.1,selected.adjustments.chromatic/900);ctx.filter=`${cssFilter(selected.adjustments)} hue-rotate(115deg)`;const shift=Math.max(1,selected.adjustments.chromatic/15);ctx.drawImage(image,sx,sy,sw,sh,-sw*factor/2+shift,-sh*factor/2,sw*factor,sh*factor);ctx.restore()}
    const mime=exportFormat==="png"?"image/png":exportFormat==="webp"?"image/webp":"image/jpeg";const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,mime,exportQuality/100));if(!blob)return;const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;const extension=exportFormat==="jpeg"?"jpg":exportFormat;link.download=`${selected.name.replace(/\.[^.]+$/,"")}-LibreLux.${extension}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExportOpen(false)
  };
  const photoTransform=selected?`translate(${selected.adjustments.offsetX/4}px,${selected.adjustments.offsetY/4}px) rotate(${selected.adjustments.rotation}deg) scale(${selected.adjustments.flipX*(selected.adjustments.perspectiveScale/100)*(1+selected.adjustments.distortion/700)},${selected.adjustments.flipY*(selected.adjustments.perspectiveScale/100)*(1+selected.adjustments.distortion/700)}) perspective(900px) rotateX(${selected.adjustments.perspectiveV/15}deg) rotateY(${selected.adjustments.perspectiveH/15}deg)`:"";
  return <main className="app-shell" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void importFiles(e.dataTransfer.files)}}>
    <input ref={fileRef} type="file" accept="image/*,.dng,.raw,.cr2,.cr3,.nef,.arw,.orf,.rw2" multiple hidden onChange={e=>e.target.files&&void importFiles(e.target.files)}/>
    <header className="topbar"><div className="brand"><div className="brand-mark"><Aperture size={19}/></div><strong>LibreLux</strong><span>by Good Tools</span></div><Tabs value={workspace} onValueChange={v=>setWorkspace(v as Workspace)}><TabsList className="workspace-tabs" variant="line"><TabsTrigger value="library"><Library/> Library <kbd>G</kbd></TabsTrigger><TabsTrigger value="develop"><SlidersHorizontal/> Develop <kbd>D</kbd></TabsTrigger><TabsTrigger value="enhance"><Sparkles/> Enhance <kbd>E</kbd></TabsTrigger></TabsList></Tabs><div className="top-actions"><ToolButton label="Undo" onClick={undo}><Undo2/></ToolButton><ToolButton label="Redo" onClick={redo}><Redo2/></ToolButton><button className="text-tool" disabled={!selected} onClick={()=>selected&&setCopiedSettings({...selected.adjustments})} title="Copy edit settings (Ctrl/Command + Shift + C)">Copy</button><button className="text-tool" disabled={!selected||!copiedSettings} onClick={()=>selected&&copiedSettings&&updateSelected(p=>({...p,adjustments:{...copiedSettings}}))} title="Paste edit settings (Ctrl/Command + Shift + V)">Paste</button><button className="primary-button" onClick={()=>setExportOpen(true)} disabled={!selected}><Download size={16}/> Export</button></div></header>
    <section className={`workspace ${showLeft?"":"left-hidden"} ${showRight?"":"right-hidden"}`}>
      <aside className="left-rail"><div className="rail-head"><span>{workspace==="library"?"Catalog":"Navigator"}</span><button onClick={()=>setShowLeft(false)} aria-label="Hide left panel"><PanelLeftClose size={16}/></button></div><button className="import-button" onClick={()=>fileRef.current?.click()}><ImagePlus size={17}/> Add photos</button><nav className="source-list" aria-label="Photo sources"><button className={filter==="all"?"selected":""} onClick={()=>setFilter("all")}><Grid3X3/> All photos <span>{photos.length}</span></button><button className={filter==="flagged"?"selected":""} onClick={()=>setFilter("flagged")}><Flag/> Picks <span>{photos.filter(p=>p.flagged).length}</span></button><button className={filter==="rated"?"selected":""} onClick={()=>setFilter("rated")}><Star/> Rated <span>{photos.filter(p=>p.rating).length}</span></button><button className={filter==="edited"?"selected":""} onClick={()=>setFilter("edited")}><SlidersHorizontal/> Edited <span>{photos.filter(p=>JSON.stringify(p.adjustments)!==JSON.stringify(defaults)).length}</span></button><button className={filter==="rejected"?"selected":""} onClick={()=>setFilter("rejected")}><X/> Rejected <span>{photos.filter(p=>p.rejected).length}</span></button></nav><div className="section-title"><span>Sort</span></div><div className="sort-grid">{([['recent','Recent'],['name','Name'],['rating','Rating'],['size','Size']] as const).map(([value,label])=><button key={value} className={sort===value?"active":""} onClick={()=>setSort(value)}>{label}</button>)}</div><div className="section-title"><span>Albums</span><button aria-label="New album">+</button></div><nav className="source-list compact"><button><FolderOpen/> Recent imports</button><button><FolderOpen/> Edited work</button><button><FolderOpen/> Five stars</button></nav>{workspace!=="library"&&<><div className="section-title"><span>Presets</span></div><div className="preset-grid">{presets.map(preset=><button key={preset.name} onClick={()=>applyPreset(preset.settings)} style={{"--tone":preset.tone} as React.CSSProperties}><i/><span>{preset.name}</span></button>)}</div></>}</aside>
      <section className="main-stage"><div className="stage-toolbar">{!showLeft&&<ToolButton label="Show left panel" onClick={()=>setShowLeft(true)}><Menu/></ToolButton>}<div className="view-tools"><ToolButton label="Before and after" active={showBefore} onClick={()=>setShowBefore(v=>!v)}><Columns2/></ToolButton><ToolButton label="Rotate left" onClick={()=>selected&&setAdjustment("rotation",selected.adjustments.rotation-90)}><RotateCcw/></ToolButton><ToolButton label="Rotate right" onClick={()=>selected&&setAdjustment("rotation",selected.adjustments.rotation+90)}><RotateCw/></ToolButton><ToolButton label="Crop" active={cropMode} onClick={()=>setCropMode(v=>!v)}><Crop/></ToolButton></div>{!showRight&&<ToolButton label="Show right panel" onClick={()=>setShowRight(true)}><PanelRightClose/></ToolButton>}</div>
        {workspace==="library"?<div className="library-view"><div className="library-heading"><div><p>{{all:"All photos",flagged:"Picks",rated:"Rated",edited:"Edited",rejected:"Rejected"}[filter]}</p><span>{filtered.length} photos · stored on this device</span></div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search filenames"/></label></div>{filtered.length?<div className="photo-grid">{filtered.map(photo=><button key={photo.id} className={`${photo.id===selectedId?"selected":""} ${photo.rejected?"rejected":""}`} onClick={()=>setSelectedId(photo.id)} onDoubleClick={()=>{setSelectedId(photo.id);setWorkspace("develop")}}><div className="thumb"><img src={photo.url} alt="" style={{filter:cssFilter(photo.adjustments)}}/>{photo.flagged&&<Flag className="pick"/>}{photo.rejected&&<X className="reject"/>}<i style={{background:labelColors[photo.label]}}/></div><strong>{photo.metadata.title||photo.name}</strong><span>{formatBytes(photo.size)}</span><div className="stars">{[1,2,3,4,5].map(n=><Star key={n} className={n<=photo.rating?"on":""}/>)}</div></button>)}</div>:<EmptyLibrary onImport={()=>fileRef.current?.click()}/>}</div>:selected?<div className="photo-stage"><div className={`photo-wrap ${cropMode?"cropping":""}`} style={{width:`${zoom}%`}}><img src={selected.url} alt={selected.name} style={{filter:showBefore?"none":cssFilter(selected.adjustments),transform:photoTransform}}/>{!showBefore&&selected.adjustments.chromatic>0&&<img className="chromatic-preview" src={selected.url} alt="" aria-hidden="true" style={{filter:`${cssFilter(selected.adjustments)} hue-rotate(115deg)`,transform:`${photoTransform} translateX(${selected.adjustments.chromatic/15}px)`,opacity:Math.min(.1,selected.adjustments.chromatic/900)}}/>}{!showBefore&&(selected.adjustments.vignette!==0||selected.adjustments.lensVignette!==0)&&<div className="vignette" style={{opacity:Math.min(.9,Math.abs(selected.adjustments.vignette-selected.adjustments.lensVignette)/115)}}/>}{!showBefore&&selected.adjustments.grain>0&&<div className="grain" style={{opacity:selected.adjustments.grain/240,backgroundSize:`${Math.max(45,180-selected.adjustments.grainSize)}px`,filter:`contrast(${1+selected.adjustments.grainRoughness/100})`}}/>}{cropMode&&<div className="crop-overlay"><div className="crop-grid"/><nav>{([[0,"Original"],[1,"1:1"],[.8,"4:5"],[1.5,"3:2"],[1.7778,"16:9"]] as const).map(([ratio,label])=><button key={label} className={selected.adjustments.cropRatio===ratio?"active":""} onClick={()=>setAdjustment("cropRatio",ratio)}>{label}</button>)}<button onClick={()=>setCropMode(false)}>Done</button></nav></div>}<span className="preview-state">{showBefore?"Original":workspace==="enhance"?"Enhanced":"Edited"}</span></div></div>:<EmptyLibrary onImport={()=>fileRef.current?.click()}/>} 
        {workspace!=="library"&&<div className="filmstrip">{photos.map(photo=><button key={photo.id} className={photo.id===selectedId?"selected":""} onClick={()=>setSelectedId(photo.id)}><img src={photo.url} alt={photo.name}/><i style={{background:labelColors[photo.label]}}/></button>)}</div>}<footer className="statusbar"><span>{selected?`${selected.name} · ${formatBytes(selected.size)}`:"No photo selected"}</span><div><ZoomOut/><Slider value={[zoom]} min={24} max={100} onValueChange={v=>setZoom(v[0])} aria-label="Preview zoom"/><ZoomIn/><span>{zoom}%</span></div></footer>
      </section>
      <aside className="right-rail"><div className="rail-head"><span>{workspace==="library"?"Photo":workspace==="develop"?"Edit":"Optics & Enhance"}</span><button onClick={()=>setShowRight(false)} aria-label="Hide right panel"><PanelRightClose size={16}/></button></div>{selected?<div className="panel-scroll"><Histogram photo={selected}/>{workspace==="library"?<LibraryInspector photo={selected} update={updateSelected} remove={removeSelected}/>:workspace==="develop"?<DevelopPanels photo={selected} setAdjustment={setAdjustment}/>:<EnhancePanels photo={selected} setAdjustment={setAdjustment} autoEnhance={autoEnhance}/>}</div>:<div className="no-selection"><Info/><p>Select or import a photo to begin.</p></div>}</aside>
    </section>
    <Dialog open={exportOpen} onOpenChange={setExportOpen}><DialogContent className="export-dialog"><DialogHeader><DialogTitle>Export photo</DialogTitle><DialogDescription>Create a finished copy. Your original stays untouched.</DialogDescription></DialogHeader><div className="export-preview">{selected&&<img src={selected.url} alt="" style={{filter:cssFilter(selected.adjustments)}}/>}<div><strong>{selected?.name.replace(/\.[^.]+$/,"")}-LibreLux.{exportFormat==="jpeg"?"jpg":exportFormat}</strong><span>{exportFormat.toUpperCase()} · {exportScale}% dimensions · sRGB</span></div></div><Panel title="File settings"><div className="choice-row"><span>Format</span>{(["jpeg","png","webp"] as const).map(value=><button key={value} className={exportFormat===value?"active":""} onClick={()=>setExportFormat(value)}>{value.toUpperCase()}</button>)}</div>{exportFormat!=="png"&&<AdjustSlider label="Quality" value={exportQuality} min={10} max={100} onChange={setExportQuality}/>}<div className="choice-row"><span>Size</span>{[25,50,100].map(value=><button key={value} className={exportScale===value?"active":""} onClick={()=>setExportScale(value)}>{value}%</button>)}</div><label className="check-row"><input type="checkbox" defaultChecked/><span>Include descriptive metadata</span></label><label className="check-row"><input type="checkbox"/><span>Add copyright watermark</span></label></Panel><DialogFooter><button className="secondary-button" onClick={()=>setExportOpen(false)}>Cancel</button><button className="primary-button" onClick={doExport}><ArrowDownToLine size={16}/> Export {exportFormat.toUpperCase()}</button></DialogFooter></DialogContent></Dialog>
  </main>
}

function EmptyLibrary({onImport}:{onImport:()=>void}){return <div className="empty-library"><div className="empty-mark"><Aperture/></div><h1>Bring your photos into focus.</h1><p>Import JPEG, PNG, WebP, or browser-supported camera files. Originals stay on this device.</p><button className="primary-button large" onClick={onImport}><ImagePlus/> Add photos</button><span>or drop files anywhere</span></div>}
function LibraryInspector({photo,update,remove}:{photo:RuntimePhoto;update:(fn:(p:RuntimePhoto)=>RuntimePhoto)=>void;remove:()=>void}){
  const setMeta=(key:keyof PhotoMetadata,value:string|string[])=>update(p=>({...p,metadata:{...p.metadata,[key]:value}}));
  return <><Panel title="Rating & labels"><div className="rating-row">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>update(p=>({...p,rating:n===p.rating?0:n}))}><Star className={n<=photo.rating?"on":""}/></button>)}</div><div className="flag-grid"><button className={`flag-button ${photo.flagged?"active":""}`} onClick={()=>update(p=>({...p,flagged:!p.flagged,rejected:false}))}><Flag/>{photo.flagged?"Picked":"Pick"}</button><button className={`flag-button reject-button ${photo.rejected?"active":""}`} onClick={()=>update(p=>({...p,rejected:!p.rejected,flagged:false}))}><X/>{photo.rejected?"Rejected":"Reject"}</button></div><div className="labels">{(Object.keys(labelColors) as Label[]).filter(l=>l!=="none").map(label=><button key={label} aria-label={`${label} label`} className={photo.label===label?"active":""} onClick={()=>update(p=>({...p,label:p.label===label?"none":label}))} style={{background:labelColors[label]}}>{photo.label===label&&<Check/>}</button>)}</div></Panel><Panel title="Description"><label className="meta-field"><span>Title</span><input value={photo.metadata.title} onChange={e=>setMeta("title",e.target.value)} placeholder="Add a title"/></label><label className="meta-field"><span>Caption</span><textarea value={photo.metadata.caption} onChange={e=>setMeta("caption",e.target.value)} placeholder="Describe this photo"/></label><label className="meta-field"><span>Creator</span><input value={photo.metadata.creator} onChange={e=>setMeta("creator",e.target.value)} placeholder="Photographer"/></label><label className="meta-field"><span>Copyright</span><input value={photo.metadata.copyright} onChange={e=>setMeta("copyright",e.target.value)} placeholder="Copyright notice"/></label></Panel><Panel title="File info"><dl className="metadata"><div><dt>Filename</dt><dd>{photo.name}</dd></div><div><dt>Type</dt><dd>{photo.type||"Image"}</dd></div><div><dt>Size</dt><dd>{formatBytes(photo.size)}</dd></div><div><dt>Added</dt><dd>{new Date(photo.createdAt).toLocaleDateString()}</dd></div></dl></Panel><Panel title="Keywords"><div className="keyword-box">{photo.metadata.keywords.map(keyword=><button key={keyword} onClick={()=>setMeta("keywords",photo.metadata.keywords.filter(k=>k!==keyword))}>{keyword} ×</button>)}</div><input className="keyword-input" placeholder="Type a keyword and press Enter" onKeyDown={e=>{if(e.key==="Enter"){const value=e.currentTarget.value.trim();if(value&&!photo.metadata.keywords.includes(value))setMeta("keywords",[...photo.metadata.keywords,value]);e.currentTarget.value=""}}}/></Panel><button className="danger-button" onClick={remove}><X/> Remove from library</button></>
}
function DevelopPanels({photo,setAdjustment}:{photo:RuntimePhoto;setAdjustment:(k:keyof Adjustments,v:number)=>void}){
  const a=photo.adjustments;
  return <>
    <div className="quick-actions"><button onClick={()=>{setAdjustment("exposure",.2);setAdjustment("highlights",-20);setAdjustment("shadows",24);setAdjustment("vibrance",12)}}><WandSparkles/> Auto</button><button onClick={()=>Object.entries(defaults).forEach(([k,v])=>setAdjustment(k as keyof Adjustments,v))}>Reset</button></div>
    <Panel title="Light"><AdjustSlider label="Exposure" value={a.exposure} min={-5} max={5} step={.05} onChange={v=>setAdjustment("exposure",v)}/><AdjustSlider label="Contrast" value={a.contrast} onChange={v=>setAdjustment("contrast",v)}/><AdjustSlider label="Highlights" value={a.highlights} onChange={v=>setAdjustment("highlights",v)}/><AdjustSlider label="Shadows" value={a.shadows} onChange={v=>setAdjustment("shadows",v)}/><AdjustSlider label="Whites" value={a.whites} onChange={v=>setAdjustment("whites",v)}/><AdjustSlider label="Blacks" value={a.blacks} onChange={v=>setAdjustment("blacks",v)}/><div className="curve"><svg viewBox="0 0 200 90"><path d="M0 90L200 0"/><path className="active" d="M0 88C38 84 52 62 91 49S150 24 200 4"/><circle cx="91" cy="49" r="3"/></svg><div><span>Point curve</span><button>Linear</button></div></div></Panel>
    <Panel title="Color"><div className="wb-row"><button onClick={()=>{setAdjustment("temperature",0);setAdjustment("tint",0)}}>As shot</button><button title="White balance eyedropper">⌾</button><button onClick={()=>setAdjustment("saturation",a.saturation===-100?0:-100)}>B&amp;W</button></div><AdjustSlider label="Temperature" value={a.temperature} onChange={v=>setAdjustment("temperature",v)}/><AdjustSlider label="Tint" value={a.tint} onChange={v=>setAdjustment("tint",v)}/><AdjustSlider label="Hue" value={a.hue} min={-180} max={180} onChange={v=>setAdjustment("hue",v)}/><AdjustSlider label="Vibrance" value={a.vibrance} onChange={v=>setAdjustment("vibrance",v)}/><AdjustSlider label="Saturation" value={a.saturation} onChange={v=>setAdjustment("saturation",v)}/><div className="color-wheel"><i/><i/><i/><span>Color Mixer · HSL</span></div></Panel>
    <Panel title="Color grading" open={false}><div className="grading-row"><span style={{"--h":a.shadowHue} as React.CSSProperties}/><div><AdjustSlider label="Shadow hue" value={a.shadowHue} min={0} max={360} onChange={v=>setAdjustment("shadowHue",v)}/><AdjustSlider label="Shadow saturation" value={a.shadowSaturation} min={0} onChange={v=>setAdjustment("shadowSaturation",v)}/></div></div><div className="grading-row"><span style={{"--h":a.midtoneHue} as React.CSSProperties}/><div><AdjustSlider label="Midtone hue" value={a.midtoneHue} min={0} max={360} onChange={v=>setAdjustment("midtoneHue",v)}/><AdjustSlider label="Midtone saturation" value={a.midtoneSaturation} min={0} onChange={v=>setAdjustment("midtoneSaturation",v)}/></div></div><div className="grading-row"><span style={{"--h":a.highlightHue} as React.CSSProperties}/><div><AdjustSlider label="Highlight hue" value={a.highlightHue} min={0} max={360} onChange={v=>setAdjustment("highlightHue",v)}/><AdjustSlider label="Highlight saturation" value={a.highlightSaturation} min={0} onChange={v=>setAdjustment("highlightSaturation",v)}/></div></div><AdjustSlider label="Balance" value={a.gradingBalance} onChange={v=>setAdjustment("gradingBalance",v)}/></Panel>
    <Panel title="Detail" open={false}><AdjustSlider label="Sharpening" value={a.sharpness} min={0} onChange={v=>setAdjustment("sharpness",v)}/><AdjustSlider label="Radius" value={a.sharpRadius} min={.5} max={3} step={.1} onChange={v=>setAdjustment("sharpRadius",v)}/><AdjustSlider label="Detail" value={a.sharpDetail} min={0} onChange={v=>setAdjustment("sharpDetail",v)}/><AdjustSlider label="Masking" value={a.sharpMasking} min={0} onChange={v=>setAdjustment("sharpMasking",v)}/><AdjustSlider label="Noise reduction" value={a.noise} min={0} onChange={v=>setAdjustment("noise",v)}/><AdjustSlider label="Color noise" value={a.colorNoise} min={0} onChange={v=>setAdjustment("colorNoise",v)}/></Panel>
    <Panel title="Effects" open={false}><AdjustSlider label="Texture" value={a.texture} onChange={v=>setAdjustment("texture",v)}/><AdjustSlider label="Clarity" value={a.clarity} onChange={v=>setAdjustment("clarity",v)}/><AdjustSlider label="Dehaze" value={a.dehaze} onChange={v=>setAdjustment("dehaze",v)}/><AdjustSlider label="Vignette" value={a.vignette} onChange={v=>setAdjustment("vignette",v)}/><AdjustSlider label="Midpoint" value={a.vignetteMidpoint} min={0} onChange={v=>setAdjustment("vignetteMidpoint",v)}/><AdjustSlider label="Feather" value={a.vignetteFeather} min={0} onChange={v=>setAdjustment("vignetteFeather",v)}/><AdjustSlider label="Grain" value={a.grain} min={0} onChange={v=>setAdjustment("grain",v)}/><AdjustSlider label="Size" value={a.grainSize} min={0} onChange={v=>setAdjustment("grainSize",v)}/><AdjustSlider label="Roughness" value={a.grainRoughness} min={0} onChange={v=>setAdjustment("grainRoughness",v)}/></Panel>
    <Panel title="Masking" badge="Local"><div className="mask-tools">{["Subject","Sky","Brush","Radial","Linear","Range"].map((name,i)=><button key={name}><span className={`mask m${i}`}/>{name}</button>)}</div><p className="panel-note">Local masks are next in the build list.</p></Panel>
  </>
}
function EnhancePanels({photo,setAdjustment,autoEnhance}:{photo:RuntimePhoto;setAdjustment:(k:keyof Adjustments,v:number)=>void;autoEnhance:()=>void}){
  const a=photo.adjustments;
  return <><div className="enhance-hero"><div><Sparkles/><span>Libre Optics</span></div><p>Camera-aware corrections and detail recovery, processed on this device.</p><button onClick={autoEnhance}><WandSparkles/> Analyze & enhance</button></div>
    <Panel title="Deep Denoise" badge={a.noise?"On":"Off"}><AdjustSlider label="Luminance" value={a.noise} min={0} onChange={v=>setAdjustment("noise",v)}/><AdjustSlider label="Color noise" value={a.colorNoise} min={0} onChange={v=>setAdjustment("colorNoise",v)}/><AdjustSlider label="Detail" value={a.sharpness} min={0} onChange={v=>setAdjustment("sharpness",v)}/><AdjustSlider label="Detail recovery" value={a.sharpDetail} min={0} onChange={v=>setAdjustment("sharpDetail",v)}/><p className="panel-note"><span className="local-dot"/> Preview and export processing run locally.</p></Panel>
    <Panel title="Optics profile" badge="Auto"><div className="profile-card"><Aperture/><div><strong>Automatic lens profile</strong><span>Manual correction remains available without metadata</span></div><Check/></div><AdjustSlider label="Lens sharpness" value={a.lensSharpness} min={0} onChange={v=>setAdjustment("lensSharpness",v)}/><AdjustSlider label="Lens vignetting" value={a.lensVignette} onChange={v=>setAdjustment("lensVignette",v)}/><AdjustSlider label="Distortion" value={a.distortion} onChange={v=>setAdjustment("distortion",v)}/><AdjustSlider label="Chromatic aberration" value={a.chromatic} min={0} onChange={v=>setAdjustment("chromatic",v)}/><AdjustSlider label="Defringe" value={a.defringe} min={0} onChange={v=>setAdjustment("defringe",v)}/></Panel>
    <Panel title="Geometry"><div className="geometry-tools"><button onClick={()=>{setAdjustment("perspectiveV",0);setAdjustment("perspectiveH",0);setAdjustment("rotation",0)}}>Auto</button><button onClick={()=>setAdjustment("rotation",0)}>Level</button><button onClick={()=>setAdjustment("perspectiveV",0)}>Vertical</button><button onClick={()=>{setAdjustment("perspectiveV",0);setAdjustment("perspectiveH",0);setAdjustment("perspectiveAspect",0)}}>Full</button></div><AdjustSlider label="Vertical" value={a.perspectiveV} onChange={v=>setAdjustment("perspectiveV",v)}/><AdjustSlider label="Horizontal" value={a.perspectiveH} onChange={v=>setAdjustment("perspectiveH",v)}/><AdjustSlider label="Rotate" value={a.rotation} min={-180} max={180} onChange={v=>setAdjustment("rotation",v)}/><AdjustSlider label="Aspect" value={a.perspectiveAspect} onChange={v=>setAdjustment("perspectiveAspect",v)}/><AdjustSlider label="Scale" value={a.perspectiveScale} min={50} max={150} onChange={v=>setAdjustment("perspectiveScale",v)}/><AdjustSlider label="X offset" value={a.offsetX} onChange={v=>setAdjustment("offsetX",v)}/><AdjustSlider label="Y offset" value={a.offsetY} onChange={v=>setAdjustment("offsetY",v)}/><div className="flip-row"><button className={a.flipX<0?"active":""} onClick={()=>setAdjustment("flipX",a.flipX*-1)}>Flip horizontal</button><button className={a.flipY<0?"active":""} onClick={()=>setAdjustment("flipY",a.flipY*-1)}>Flip vertical</button></div></Panel>
    <Panel title="Local contrast" open={false}><AdjustSlider label="Fine" value={a.texture} onChange={v=>setAdjustment("texture",v)}/><AdjustSlider label="Medium" value={a.clarity} onChange={v=>setAdjustment("clarity",v)}/><AdjustSlider label="Atmosphere" value={a.dehaze} onChange={v=>setAdjustment("dehaze",v)}/></Panel>
    <Panel title="Film rendering" open={false}><div className="film-options"><button onClick={()=>{setAdjustment("saturation",0);setAdjustment("contrast",0);setAdjustment("grain",0)}}>Digital neutral</button><button onClick={()=>{setAdjustment("saturation",-8);setAdjustment("contrast",18);setAdjustment("temperature",-4)}}>Classic chrome</button><button onClick={()=>{setAdjustment("saturation",-100);setAdjustment("contrast",24);setAdjustment("grain",28)}}>Fine grain B&amp;W</button><button onClick={()=>{setAdjustment("temperature",16);setAdjustment("contrast",-6);setAdjustment("grain",16)}}>Warm negative</button></div></Panel>
  </>
}
